/*
 * Copyright (C) 2017 Riccardo De Benedictis <riccardo.debenedictis@istc.cnr.it>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package it.cnr.istc.ratio.gui;

import it.cnr.istc.ratio.api.CausalGraph;
import it.cnr.istc.ratio.api.Solver;
import it.cnr.istc.ratio.api.State;
import javax.swing.JOptionPane;

/**
 *
 * @author Riccardo De Benedictis <riccardo.debenedictis@istc.cnr.it>
 */
public class CausalGraphJFrame extends javax.swing.JFrame {

    private final CausalGraph cg;

    /**
     * Creates new form CausalGraphJFrame
     */
    public CausalGraphJFrame(CausalGraph cg) {
        initComponents();
        this.cg = cg;
        cg.addCausalGraphListener(causalGraphDisplay);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        causalGraphDisplay = new it.cnr.istc.ratio.gui.CausalGraphDisplay();

        fc.setMultiSelectionEnabled(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Causal graph");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(causalGraphDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(causalGraphDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cg.removeCausalGraphListener(causalGraphDisplay);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CausalGraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Solver s = new Solver();
        CausalGraph cg = new CausalGraph(s);
        CausalGraphJFrame frame = new CausalGraphJFrame(cg);
        frame.setVisible(true);
        if (!s.read(new String[]{"C:\\Users\\sydde\\Desktop\\test_sv_0.rddl"})) {
            JOptionPane.showMessageDialog(frame, "The initial problem is inconsistent.", "o-ratio", JOptionPane.WARNING_MESSAGE);
        }
        if (!s.solve()) {
            JOptionPane.showMessageDialog(frame, "The problem is unsolvable.", "o-ratio", JOptionPane.WARNING_MESSAGE);
        }
        State state = s.getState();
        cg.dispose();
        s.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private it.cnr.istc.ratio.gui.CausalGraphDisplay causalGraphDisplay;
    private javax.swing.JFileChooser fc;
    // End of variables declaration//GEN-END:variables
}
