/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_cnr_istc_ratio_api_CausalGraph */

#ifndef _Included_it_cnr_istc_ratio_api_CausalGraph
#define _Included_it_cnr_istc_ratio_api_CausalGraph
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    initialise
     * Signature: (J)J
     */
    JNIEXPORT jlong JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_initialise
    (JNIEnv *, jobject, jlong);

    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    dispose
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_dispose
    (JNIEnv *, jobject);

    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    get_flaw_cost
     * Signature: (J)D
     */
    JNIEXPORT jdouble JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_get_1flaw_1cost
    (JNIEnv *, jobject, jlong);

    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    get_flaw_state
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_get_1flaw_1state
    (JNIEnv *, jobject, jlong);

    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    get_resolver_cost
     * Signature: (J)D
     */
    JNIEXPORT jdouble JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_get_1resolver_1cost
    (JNIEnv *, jobject, jlong);

    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    get_resolver_state
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_get_1resolver_1state
    (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
