/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_cnr_istc_ratio_api_CausalGraph */

#ifndef _Included_it_cnr_istc_ratio_api_CausalGraph
#define _Included_it_cnr_istc_ratio_api_CausalGraph
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    initialise
     * Signature: (J)J
     */
    JNIEXPORT jlong JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_initialise(JNIEnv *, jobject, jlong);

    /*
     * Class:     it_cnr_istc_ratio_api_CausalGraph
     * Method:    dispose
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_it_cnr_istc_ratio_api_CausalGraph_dispose(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
